name: 'Execute N-BKP Cisco'
env:
  device_username: ${{ secrets.DEVICE_USERNAME }}
  device_password: ${{ secrets.DEVICE_PASSWORD }}
  #opsgenie_api_key: ${{secrets.OPSGENIE_API_KEY}}

jobs: 
  execute_scripts:
    runs-on: [myrunner]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Run Pyhton Scripts
        run: | 
          python3 environment/cisco/cisco.py        
          pwd
      - name: Check created files
        run: |
           ls -la /pathtofile/*.txt
           
